services:
  - type: web
    name: appointment-scheduler-api
    env: docker
    region: ohio
    plan: free
    dockerContext: .
    dockerfilePath: src/Web.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
      - key: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
        value: "false"
    disk:
      name: sqlite-data
      mountPath: /app/Data
      sizeGB: 1
