// <auto-generated />
using System;
using Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Domain.Availabilities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_week");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_availabilities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_availabilities_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_availabilities_user_id1");

                    b.ToTable("availabilities", "public");
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type_id");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("google_event_id");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_bookings_event_type_id");

                    b.HasIndex("GuestEmail")
                        .HasDatabaseName("ix_bookings_guest_email");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_bookings_start_time");

                    b.HasIndex("UserId", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_user_id_start_time")
                        .HasFilter("\"Status\" = 'Confirmed'");

                    b.ToTable("bookings", "public");
                });

            modelBuilder.Entity("Domain.CalendarSettings.CalendarSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("AllowGuestNotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_guest_notes");

                    b.Property<bool>("AllowOverlapBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_overlap_booking");

                    b.Property<int>("BufferAfterMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("buffer_after_minutes");

                    b.Property<int>("BufferBeforeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("buffer_before_minutes");

                    b.Property<bool>("CheckGoogleCalendarConflicts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("check_google_calendar_conflicts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CustomAvailabilityEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_availability_end");

                    b.Property<DateTime?>("CustomAvailabilityStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_availability_start");

                    b.Property<TimeOnly>("DefaultEndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_end_time");

                    b.Property<TimeOnly>("DefaultStartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_start_time");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("google_calendar_id");

                    b.Property<int?>("MaxBookingsPerDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_bookings_per_day");

                    b.Property<int?>("MaxBookingsPerWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_bookings_per_week");

                    b.Property<int>("MaximumDaysInAdvance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maximum_days_in_advance");

                    b.Property<int>("MinimumNoticeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minimum_notice_minutes");

                    b.Property<int?>("MinimumSchedulingGap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minimum_scheduling_gap");

                    b.Property<int>("ReminderMinutesBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1440)
                        .HasColumnName("reminder_minutes_before");

                    b.Property<bool>("RequireGuestPhone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("require_guest_phone");

                    b.Property<int>("RollingDaysAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30)
                        .HasColumnName("rolling_days_available");

                    b.Property<bool>("SendConfirmationEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("send_confirmation_email");

                    b.Property<bool>("SendReminderEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("send_reminder_email");

                    b.Property<int>("SlotIntervalMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_interval_minutes");

                    b.Property<bool>("SyncToGoogleCalendar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_to_google_calendar");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("WelcomeMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("welcome_message");

                    b.HasKey("Id")
                        .HasName("pk_calendar_setting");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_calendar_setting_user_id");

                    b.ToTable("calendar_setting", "public");
                });

            modelBuilder.Entity("Domain.EventTypes.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buffer_minutes");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_event_types");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_types_user_id");

                    b.ToTable("event_types", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("GoogleAccessToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("google_access_token");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("google_id");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("google_refresh_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("picture_url");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Availabilities.Availability", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availabilities_users_user_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany("Availabilities")
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_availabilities_users_user_id1");
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Domain.EventTypes.EventType", "EventType")
                        .WithMany("Bookings")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_event_types_event_type_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.Navigation("EventType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.CalendarSettings.CalendarSetting", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.CalendarSettings.CalendarSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_setting_users_user_id");
                });

            modelBuilder.Entity("Domain.EventTypes.EventType", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("EventTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_types_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.EventTypes.EventType", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Bookings");

                    b.Navigation("EventTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
